# DynamicWeather Configuration File

api-key: "" # Signup to visualcrossing.com and paste your api-key here
weather-address: "Auckland" # Pick the city you would like to match with
weather-worldname: "world" # World that will take effect

use-true-weather: true # Make it rain/clear
use-true-temperature: true  # Make player freeze/overheat to death if not wearing enough or too much armor
use-true-time: false # DayTime will be equal to your timezone instead of minecraft's one
